### ISSUE TITLE
NT Cybernetics

### ISSUE THREAD

**Issue by CannibalSmiley** [Mannatwo/Neurotrauma#4]
**What mod is this request for?**
Neurotrauma, NT surgery plus, NT cybernetics or NT pharmacy

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Details like recipes, prices, locations and function should be included.

**Describe alternatives you've considered**

**Additional context**

**Comment by Mannatwo** [comment]
this is just the template without an actual feature in it

**Comment by CannibalSmiley** [comment]
I thought I had filled it out?
