### ISSUE TITLE
Troll

### ISSUE THREAD

**Issue by evilfactory** [Mannatwo/Neurotrauma#5]
**What mod is this request for?**
Neurotrauma

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i look at myself, and i see no troll

**Describe the solution you'd like**
Troll Fuel: 2 compound n + 1 plasma cutter + 1 welding tool
Troll Poster: Black and White paint
Troll Syringe: 1 IC4-Block + Morphine (the syringe is disguised as morphine)

**Describe alternatives you've considered**
There's no alternative, this is perfect.

**Additional context**
![image](https://user-images.githubusercontent.com/36804725/169892107-0f0677e7-5349-4fea-8026-b3aca1993f2b.png)

**Comment by Mannatwo** [comment]
feature requests are dead
