### ISSUE TITLE
Feature Request for NT Cybernetics

### ISSUE THREAD

**Issue by CannibalSmiley** [Mannatwo/Neurotrauma#6]
**What mod is this request for?**
Request is for NT Cybernetics

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I suggest adding cybernetics for the torso and head, as well as some variety to the limb cybernetics:
-Cybernetic Lungs (Allow prolonged swimming underwater with slowed O2 loss.
-Cybernetic Heart (Functions like an AED when Cardiac Arrest occurs)
-Cybernetic Kidneys (Slows the effect of paralysis, as well as other poisons)
-Cybernetic Liver (Prevents drunkeness)
-Cybernetic Bone Marrow (Reduces physical damage and blunt force trauma, as well as fracture chance by 75%)
-Cybernetic Integumentary System (Makes patient immune to crush damage up to 8000m in depth, reduces damage from lacerations and bite wounds by 75%, extremely expensive to make. Is cosmetic, and adds "nodes" and visible cable running along the skin.)

-Cybernetic Brain (Boosts all skills by +10, but is extremely expensive to make)
-Cybernetic Jaw (Allows ramming attack similar to Mudraptor Genes, cosmetic)
-Cybernetic Visor (Functions like a Medical Scanner from the base game, as well as thermal imaging like the Thermal Goggles. Cosmetic)

-Alternative Limb Cybernetics:
--Brute Arms (Larger, more "muscular" arms with pistons replacing the biceps. Increases melee damage by 75%. Can carry 1 crate per hand, as well as other two-handed items. Cosmetic)
--Engineer Arms (Skinnier, but the hands are replaced with "tool" fingers that increase repair speed by 125%. Cannot carry crates or two handed items. Cosmetic)
--Cyber-Blade Arm (Replaces forearm of limb with an elongated blade, deals 150% melee damage and 50% burn damage. Unable to hold items. Cosmetic)
--Raptor Legs (Replaces legs with digitate legs, making patient taller and 20% faster. Cosmetic) (Use Velociraptor leg for reference)
--Crusher Legs (Replaces thigh with a thicker variant, as well as replacing the foot, reducing fall damage by 75%. Cosmetic) (Use grasshopper leg for reference)
--Mantis Legs (Replaces entire leg with a skinny and brittle alternative that is multi-segmented, but increases movement speed by 100%. Cosmetic) (Use cockroach leg for reference)

**Additional context**
I feel as though NT Cybernetics has a great amount of room for improvement, and could easily be improved with the implementation of new cybernetics such as these. Feel free to change the names of each cybernetic to your liking, I'm also leaving the design to your discretion, as the look of the other cybernetics is already pretty good. Thanks for your time Mannatu!

**Comment by Mannatwo** [comment]
feature requests are dead

**Comment by CannibalSmiley** [comment]
I had asked you on Discord if I could make a suggestion for NTC and you
gave me the github link. I DM'd you my suggestions
