### ISSUE TITLE
Gips reforged[Feature request] 

### ISSUE THREAD

**Issue by Magos-biologis** [Mannatwo/Neurotrauma#7]
**What mod is this request for?**
Neurotrauma

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Gips breaks down after taking damage or when bone heals. People will have to avoid damage, and no more cyborg-man, with all limbs gipsed. It will be more realistic, I think.

**Describe alternatives you've considered**
Im considered to write in #feature request, but it doesnt now exist.

**Additional context**
![Screenshot_3](https://user-images.githubusercontent.com/78676550/169904583-445d3c25-6ecb-42e7-93f8-ad16abf9f864.png)

**Comment by Mannatwo** [comment]
feature requests are dead
